# Generated by Django 5.0.2 on 2024-02-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_createproduct_delete_profile_delete_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='createproduct',
            name='category',
            field=models.ManyToManyField(to='product.category', verbose_name='دسته بندی'),
        ),
    ]
