# Generated by Django 5.0.2 on 2024-02-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
    ]
