# Generated by Django 5.0.2 on 2024-02-24 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_comment_product_comment_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول'),
        ),
    ]
