# Generated by Django 5.0.2 on 2024-02-24 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 2, 24, 11, 33, 24, 853625, tzinfo=datetime.timezone.utc)),
        ),
    ]
