# Generated by Django 5.0.2 on 2024-02-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='نام دسته بندی'),
        ),
    ]
