# Generated by Django 5.0.2 on 2024-02-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_category_url_name_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='newist_products',
            field=models.BooleanField(default=True),
        ),
    ]
