# Generated by Django 5.0.2 on 2024-02-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_favorite_products_product_newist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='newist_products',
            field=models.BooleanField(default=False),
        ),
    ]
