# Generated by Django 5.0.2 on 2024-02-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_product_newist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='product.category', verbose_name='دسته بندی'),
        ),
    ]
