# Generated by Django 5.0.2 on 2024-02-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='product.category', verbose_name='دسته بندی'),
        ),
    ]
