# Generated by Django 5.0.2 on 2024-02-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_name',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
