# Generated by Django 5.0.2 on 2024-02-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_rename_user_visitedproduct_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedproduct',
            name='user_id',
        ),
    ]
