# Generated by Django 5.0.2 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_visitedproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedproduct',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
