# Generated by Django 5.0.2 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_visitedproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
