# Generated by Django 5.0.2 on 2024-02-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
