# Generated by Django 5.0.2 on 2024-02-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_alter_sitesetting_site_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.URLField(verbose_name='ادرس')),
                ('image', models.ImageField(upload_to='files/banner_image', verbose_name='عکس بنر')),
                ('position', models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_details', 'صفحه جزییات محصولات')], max_length=200, verbose_name='محل قرار گیری')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'لیست بنر',
                'verbose_name_plural': 'لیست بنر ها',
            },
        ),
    ]
